### ISSUE TITLE
Weird file format and VSCode spelling??

### ISSUE THREAD

**Issue by SourLemonJuice** [Merrit/kde-dolphin-open-vscode#11]
So why does each line of the [openVSCode.desktop](https://github.com/Merrit/kde-dolphin-open-vscode/blob/master/openVSCode.desktop) start with a space?\
And `VSCode` is written as `VS Code`, would anyone really say that?

**Comment by SourLemonJuice** [comment]
Wow, I'm sorry Microsoft really calls it `VS Code`

> VS Code supports almost every major programming language...

Okey... (º﹃º )

**Comment by Merrit** [comment]
> So why does each line of the [openVSCode.desktop](https://github.com/Merrit/kde-dolphin-open-vscode/blob/master/openVSCode.desktop?rgh-link-date=2024-11-14T16%3A33%3A35Z) start with a space?

No idea, but will fix it. Thanks! :blue_heart: 

> Wow, I'm sorry Microsoft really calls it `VS Code`

Yep, I originally had everything written as `VSCode` in several repositories and groups I work in, until someone pointed out to me that they do it that way and it would be best to follow for consistency. :rofl:
