### ISSUE TITLE
a how to install would be nive

### ISSUE THREAD

**Issue by marozsas** [Merrit/kde-dolphin-open-vscode#2]
Hi, 
New to KDE here, would be nice to have a install procedure.
Where it is supposed to save that .desktop file ?
Any other activation procedure is needed ?

PS: I manage to figure out that I should save the desktop file to "~/.local/share/kservices5/ServiceMenus/" pretty obscure path.
Anyway, a still think that mention it on readme would help others. Thanks !

**Comment by Merrit** [comment]
Didn't occur to me to write instructions, since it is presumed most people will install from the built-in extension browser.

I added some brief instructions to the README. Thanks for the suggestion! :blue_heart:  :)

**Comment by marozsas** [comment]
Oh, yes ? I didn't know it was possible to install through a browser extension ! good to know. 
Thanks for adding the installation instruction.

**Comment by Merrit** [comment]
Sure, in Dolphin you go to Configure -> Context Menu -> Download New Services

![image](https://user-images.githubusercontent.com/9575627/176518871-de11c077-52f5-44f3-a258-ae74a0e7c0e8.png)

Then when you search for things, they have a convenient install button that handles it all for you:

![image](https://user-images.githubusercontent.com/9575627/176519012-6bbf827b-4d5c-4991-b4d4-f21127ec2b1f.png)
